"""empty message

Revision ID: 076264d28940
Revises: 55bea06eed78
Create Date: 2026-04-25 10:51:11.396897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076264d28940'
down_revision = '55bea06eed78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('prenom', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('sexe', sa.Enum('M', 'F', name='sexetype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
