"""suppression de la colonne birthdate

Revision ID: 44d7b6512fd7
Revises: 86826529166b
Create Date: 2026-04-18 09:49:55.226444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d7b6512fd7'
down_revision = '86826529166b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
